<?php

function bglobal_angular_preprocess_block(&$variables) {
  // Affect variable passed to block.html.twig and all of it's children
  if (!empty($variables['theme_hook_original'] == 'block')) {
    $plugin_id = $variables['derivative_plugin_id'];
    $module_handler = \Drupal::service('module_handler');
    $module_path = file_create_url($module_handler->getModule('bglobal_angular')->getPath());  
    if ($plugin_id == 'info_sessions_advising') {
      $variables['#attached']['drupalSettings'][$plugin_id]['imagePath'] = $module_path . "/images/";
    }
    if ($plugin_id == 'spocc') {
      $variables['#attached']['drupalSettings'][$plugin_id]['templatesPath'] = $module_path . "/components/spocc/templates/";
    }
  }
}


// preprocess functions inject new variables
// Same thing we do on twig to make variables available from node content
// Always use if statements to make it as specific as possible so it only runs when it finds that thing. 
// 
// For Image Path stuff:
// https://drupal.stackexchange.com/questions/184329/using-images-in-custom-module-not-through-css
// 
// Sample Debug:
// dd($variables); (breaks everything, shows all variables)
// echo '<pre>' . __FILE__ . ':' . __LINE__;
// var_dump($variables['#attached']['drupalSettings']) ;
// echo ' </pre>';
