# @file
# Default build configuration properties.
#
# This file may be customized for your project. The full set of default values can be
# found in the-build's repository.
# @see https://github.com/palantirnet/the-build/blob/release-2.0/defaults.yml

# These properties are used when building the settings.php and settings.yml for your
# Drupal site, and by some of the targets in the default build.xml file.
# @see .the-build/drupal/services.build.yml
# @see .the-build/drupal/settings.build.php
build:
  host: pantheon

drupal:
  root: "web"

  twig:
    debug: true

  # Comma-separated list of directories that should be present for Drupal development.
  # EDIT: We removed creating the config split directories since they are different.
  create_dirs: "${drupal.root}/modules/custom,${drupal.root}/themes/custom,${drupal.root}/profiles/custom"

  sites:
    default:
      # REQUIRED: Name of the sites subdirectory where the `settings.php` file
      # should live.
      dir: default

      # REQUIRED: Your site's URI; the default should be the URI of your local
      # development environment.
      uri: "https://global.ddev.site"

      # OPTIONAL: Drupal hash salt defaults to "temporary".
      hash_salt: "IifzfbSZwhlFEBkbBzoKeXKfjVJMFkqXMlqJStlLlXOEPqHKhkRzOAryhyyjXlmI"

      database:
        username: "db"
        password: "db"
        host: "127.0.0.1"

      settings:
        # Use the Pantheon convention
        file_private_path: sites/default/files/private

      # Path to the Drupal config directory, relative to the Drupal root.
      config_sync_directory: "../config/drupal"

# To build an artifact from your code, add the URL to your artifact git repository.
# @see https://github.com/palantirnet/the-build/blob/release-2.0/defaults.yml

artifact:
  gitignore_template: ".the-build/artifact/gitignore"
  git:
    remote: "ssh://codeserver.dev.7a43f5b4-f7a9-4542-a2f3-eeda766d848b@codeserver.dev.7a43f5b4-f7a9-4542-a2f3-eeda766d848b.drush.in:2222/~/repository.git"

    # Name of a branch to use as the base, if the artifact.remote_branch does not yet
    # exist on the artifact.git.remote repository.
    remote_base_branch: master

    # Name to use for the git remote on the artifact repository.
    remote_name: origin

# Configuration for building the style guide.
#
# Use these properties if you're using a Composer + Yarn install process for your
# style guide and need to customize the location or the build command.
styleguide:
  # Location of the style guide, relative to the project root.
  root: "${drupal.root}/themes/custom/bglobal"
  # Command to compile the style guide assets, for use during the build and artifact steps.
  command: 'yarn && yarn styleguide'
