module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  bglobal_angular: 0
  bglobal_pardot: 0
  bglobal_test_content: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  components: 0
  config: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  default_content: 0
  devel: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  help: 0
  image: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pdb: 0
  pdb_ng2: 0
  rdf: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  term_condition: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  workbench: 0
  workbench_access: 0
  workflows: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  bartik: 0
  seven: 0
  bglobal: 0
  stark: 0
  stable: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
