<?php

/**
 * @file
 * Drupal hook implementations.
 */

/**
 * Implements hook_theme().
 */
function bglobal_pardot_theme() {
  return array(
    'bglobal_pardot_form' => array(
      // Proof of concept for configurable variables.
      'variables' => [
        'action_url' => 'https://go.pardot.com/l/102272/2016-11-04/2klckm',
        'success_message' => NULL,
        'submit_label' => 'Submit',
        'fields' => [],
      ],
    ),
  );
}

/**
 * Prepares variables for Pardot form templates.
 *
 * Default template: bglobal-pardot-form.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - action_url: The form submit URL.
 *   - success_message: The message to display on success.
 *   - submit_label: The label for the submit button.
 *   - fields: an array of field information.
 */
function template_preprocess_bglobal_pardot_form(&$variables) {
  // TODO: page specific variables.
}
