<?php

/**
 * @file
 * Drupal hook implementations.
 */

/**
 * Implements hook_theme().
 */
function bglobal_pardot_theme() {
  return array(
    'bglobal_pardot_form' => array(
      'variables' => [
        'action_url' => 'https://go.pardot.com/l/102272/2016-11-04/2klckm',
        'success_message' => 'Success!',
        'submit_label' => 'Submit',
        'fields' => [
          'firstname' => [
            'label' => 'First Name',
            'type' => 'text',
            'required' => TRUE,
          ],
          'lastname' => [
            'label' => 'Last Name',
            'type' => 'text',
            'required' => TRUE,
          ],
          'email' => [
            'label' => 'Email',
            'type' => 'text',
            'required' => TRUE,
          ],
          'status' => [
            'label' => 'Status',
            'type' => 'select',
            'options' => ['Student', 'Professional'],
            'default_value' => 'Professional',
          ],
          'question' => [
            'label' => 'Question',
            'type' => 'textarea',
            'rows' => '5',
            'cols' => '20',
            'required' => FALSE,
          ],
        ],
      ],
    ),
  );
}

/**
 * Prepares variables for Pardot form templates.
 *
 * Default template: bglobal-pardot-form.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - action_url: The form submit URL.
 *   - message: The message to display on success.
 */
function template_preprocess_bglobal_pardot_form(&$variables) {
  // TODO: page specific variables.
}
