<?php

/**
 * Install functions for default content.
 */

/**
 * @inheritdoc

function bglobal_test_content_install($is_syncing) {
  // All our custom blocks are used by Layouts, so register them.
  $uuids = [
    '3e8afb12-ae97-4876-9ec9-958108a8c5ef' => 3,
    '546bae8e-2d73-4871-9b57-1a53a7818a43' => 4,
    'e349a631-440f-4ffc-b6de-6e8bce48e649' => 5,
    '0b671609-3b3f-4624-90ca-0f0a9c2abef7' => 6,
  ];
  $block_storage = \Drupal::entityTypeManager()->getStorage('block_content');
  $db = \Drupal::database();
  foreach ($uuids as $uuid => $revision_id) {
    if ($block = $block_storage->loadByProperties(['uuid' => $uuid])) {
      $values = [
        'block_content_id' => $block->id(),
        'layout_entity_type' => 'entity_view_display',
        'layout_entity_id' => 'node.program.default'
      ];
      $db->insert('inline_block_usage')->fields($values)->execute();
    }
  }
}
 */
